version: '3'

services:
  app:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/var/www/app
      - ./tmp/db:/var/www/app/db/*.sqlite3
    ports:
      - "3000:3000"